/* Generated by bin2c, do not edit manually */
#ifndef __chan_size_3001_instructions_h_included
#define __chan_size_3001_instructions_h_included

/* Contents of file chan_size_3001-instructions.bin */
extern const long int chan_size_3001_instructions_bin_size;
extern const unsigned char chan_size_3001_instructions_bin[192064];

/* File table comprising original file name, address and size */
typedef struct {
	char *entryName;
	const char *data;
	long int size;
} TFileTableEntry;

extern const unsigned int fileTableSize;
extern const TFileTableEntry fileTable[];

#endif    /* __chan_size_3001_instructions_h_included */
