/* Generated by bin2c, do not edit manually */
#ifndef __chan_size_1_instructions_h_included
#define __chan_size_1_instructions_h_included

/* Contents of file chan10-instructions.bin */
extern const long int chan_size_1_instructions_bin_size;
extern const unsigned char chan_size_1_instructions_bin[64];

#endif    /* __chan_size_1_instructions_h_included */
