# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/john.meisner/Workspace/ultra96_bex/vivado/constraints/_i_bitgen.xdc

# XDC: C:/Users/john.meisner/Workspace/ultra96_bex/vivado/constraints/_i_io.xdc

# XDC: C:/Users/john.meisner/Workspace/ultra96_bex/vivado/constraints/vivado_target.xdc

# XDC: C:/Users/john.meisner/Workspace/ultra96_bex/vivado/constraints/_i_io_pmod_j5.xdc

# Block Designs: bd/zusys/zusys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys || ORIG_REF_NAME==zusys} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlconcat_0_0/zusys_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_xlconcat_0_0 || ORIG_REF_NAME==zusys_xlconcat_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_axi_timer_0_0/zusys_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_axi_timer_0_0 || ORIG_REF_NAME==zusys_axi_timer_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_blk_mem_gen_0_7/zusys_blk_mem_gen_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_blk_mem_gen_0_7 || ORIG_REF_NAME==zusys_blk_mem_gen_0_7} -quiet] -quiet

# IP: bd/zusys/ip/zusys_blk_mem_gen_1_0/zusys_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_blk_mem_gen_1_0 || ORIG_REF_NAME==zusys_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_blk_mem_gen_2_1/zusys_blk_mem_gen_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_blk_mem_gen_2_1 || ORIG_REF_NAME==zusys_blk_mem_gen_2_1} -quiet] -quiet

# IP: bd/zusys/ip/zusys_blk_mem_gen_3_0/zusys_blk_mem_gen_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_blk_mem_gen_3_0 || ORIG_REF_NAME==zusys_blk_mem_gen_3_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_axi_bram_ctrl_4_1/zusys_axi_bram_ctrl_4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_axi_bram_ctrl_4_1 || ORIG_REF_NAME==zusys_axi_bram_ctrl_4_1} -quiet] -quiet

# IP: bd/zusys/ip/zusys_axi_bram_ctrl_5_1/zusys_axi_bram_ctrl_5_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_axi_bram_ctrl_5_1 || ORIG_REF_NAME==zusys_axi_bram_ctrl_5_1} -quiet] -quiet

# IP: bd/zusys/ip/zusys_axi_bram_ctrl_6_1/zusys_axi_bram_ctrl_6_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_axi_bram_ctrl_6_1 || ORIG_REF_NAME==zusys_axi_bram_ctrl_6_1} -quiet] -quiet

# IP: bd/zusys/ip/zusys_axi_bram_ctrl_7_0/zusys_axi_bram_ctrl_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_axi_bram_ctrl_7_0 || ORIG_REF_NAME==zusys_axi_bram_ctrl_7_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_axi_gpio_0_0/zusys_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_axi_gpio_0_0 || ORIG_REF_NAME==zusys_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_proc_sys_reset_0_1/zusys_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_proc_sys_reset_0_1 || ORIG_REF_NAME==zusys_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/zusys/ip/zusys_rst_ps8_0_100M_0/zusys_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_rst_ps8_0_100M_0 || ORIG_REF_NAME==zusys_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_smartconnect_0_0/zusys_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_smartconnect_0_0 || ORIG_REF_NAME==zusys_smartconnect_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_smartconnect_2_0/zusys_smartconnect_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_smartconnect_2_0 || ORIG_REF_NAME==zusys_smartconnect_2_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_zynq_ultra_ps_e_0_1/zusys_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zusys_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==zusys_zynq_ultra_ps_e_0_1} -quiet] -quiet

# XDC: c:/Users/john.meisner/Workspace/ultra96_bex/vivado/test_board.gen/sources_1/bd/zusys/zusys_ooc.xdc
