# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/miken/Workspace/ultra96_bex/vivado/test_board.srcs/sources_1/bd/zusys/ip/zusys_axi_gpio_0_0/zusys_axi_gpio_0_0.xci
# IP: The module: 'zusys_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/miken/Workspace/ultra96_bex/vivado/test_board.gen/sources_1/bd/zusys/ip/zusys_axi_gpio_0_0/zusys_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/miken/Workspace/ultra96_bex/vivado/test_board.gen/sources_1/bd/zusys/ip/zusys_axi_gpio_0_0/zusys_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/miken/Workspace/ultra96_bex/vivado/test_board.gen/sources_1/bd/zusys/ip/zusys_axi_gpio_0_0/zusys_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/miken/Workspace/ultra96_bex/vivado/test_board.srcs/sources_1/bd/zusys/ip/zusys_axi_gpio_0_0/zusys_axi_gpio_0_0.xci
# IP: The module: 'zusys_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/miken/Workspace/ultra96_bex/vivado/test_board.gen/sources_1/bd/zusys/ip/zusys_axi_gpio_0_0/zusys_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/miken/Workspace/ultra96_bex/vivado/test_board.gen/sources_1/bd/zusys/ip/zusys_axi_gpio_0_0/zusys_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/miken/Workspace/ultra96_bex/vivado/test_board.gen/sources_1/bd/zusys/ip/zusys_axi_gpio_0_0/zusys_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zusys_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
