on: [push] 
jobs:
    build:
      runs-on: self-hosted
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Build with XSCT
          run: |
            /c/xilinx/vitis/2022.2/bin/xsct.bat -eval "source build_script.tcl" 
